export const PASSPORT_COUNTRIES = [
  'Algeria',
  'Angola',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belgium',
  'Bolivia',
  'Brazil',
  'Bulgaria',
  'Cambodia',
  'Canada',
  'Chile',
  'China',
  'Colombia',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'Estonia',
  'Ethiopia',
  'Finland',
  'France',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kuwait',
  'Laos',
  'Latvia',
  'Lithuania',
  'Luxembourg',
  'Malaysia',
  'Maldives',
  'Malta',
  'Mexico',
  'Mongolia',
  'Morocco',
  'Myanmar',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nigeria',
  'Norway',
  'Oman',
  'Pakistan',
  'Panama',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Saudi Arabia',
  'Serbia',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'South Africa',
  'South Korea',
  'Spain',
  'Sri Lanka',
  'Sweden',
  'Switzerland',
  'Tanzania',
  'Thailand',
  'Tunisia',
  'Turkey',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vietnam',
  'Zimbabwe',
] as const;

export const DESTINATION_COUNTRIES = [
  'Argentina',
  'Australia',
  'Austria',
  'Bahrain',
  'Belgium',
  'Brazil',
  'Bulgaria',
  'Canada',
  'Chile',
  'China',
  'Colombia',
  'Croatia',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Egypt',
  'Estonia',
  'Ethiopia',
  'Finland',
  'France',
  'Germany',
  'Greece',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Ireland',
  'Italy',
  'Japan',
  'Kazakhstan',
  'Kenya',
  'Kuwait',
  'Latvia',
  'Lithuania',
  'Luxembourg',
  'Malaysia',
  'Malta',
  'Mexico',
  'Netherlands',
  'New Zealand',
  'Nigeria',
  'Norway',
  'Oman',
  'Panama',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Saudi Arabia',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'South Africa',
  'South Korea',
  'Spain',
  'Sweden',
  'Switzerland',
  'Taiwan',
  'Thailand',
  'Turkey',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uzbekistan',
  'Vietnam',
] as const;

export const REGIONS = [
  {
    name: 'Asia Pacific',
    description: 'Major transit hubs across East Asia, Southeast Asia, South Asia, and Oceania.',
  },
  {
    name: 'Europe',
    description: 'Airside and terminal-connected hotels at leading European hub airports.',
  },
  {
    name: 'North America',
    description: 'Airport hotels and sleep options across the US, Canada, and Mexico.',
  },
  {
    name: 'Middle East',
    description: 'World-class transit accommodation at the Gulf region\'s busiest connecting airports.',
  },
  {
    name: 'Africa',
    description: 'Transit and landside hotel options at key African gateway airports.',
  },
  {
    name: 'Latin America',
    description: 'Airport stays across Central and South America\'s major hub cities.',
  },
] as const;

export const SLEEP_POD_TYPES = ['capsule_hotel', 'sleep_pods'] as const;

export const PRICE_TIERS = {
  BUDGET_MAX: 100,
  MODERATE_MAX: 200,
} as const;

export const SCORING = {
  BASE: 50,

  SHORT_LAYOVER_HOURS: 4,
  MEDIUM_LAYOVER_HOURS: 8,
  LONG_LAYOVER_HOURS: 12,
  SHORT_POD_BONUS_HOURS: 6,

  SHORT_POD_BONUS: 25,
  SHORT_HOTEL_PENALTY: -10,
  MEDIUM_AIRSIDE_TRANSIT_BONUS: 20,
  MEDIUM_POD_BONUS: 10,
  LONG_HOTEL_BONUS: 20,
  LONG_TERMINAL_BONUS: 20,
  EXTENDED_HOTEL_BONUS: 20,
  EXTENDED_TERMINAL_BONUS: 20,

  AIRSIDE_BONUS: 30,
  TERMINAL_CONNECTED_BONUS: 20,

  NO_IMMIGRATION_BONUS: -25,
  TRANSIT_VISA_IMMIGRATION_PENALTY: -40,

  BUDGET_PRICE_BONUS: 10,
  MODERATE_PRICE_BONUS: 5,

  POD_SHORT_BONUS: 15,

  SCORE_MIN: 0,
  SCORE_MAX: 100,

  ELIGIBILITY_ELIGIBLE_WITH_WARNING: -10,
  ELIGIBILITY_NOT_RECOMMENDED: -50,
  ELIGIBILITY_UNKNOWN: -20,
  NO_IMMIGRATION_REQUIRED_BONUS: 15,
} as const;

export const PROPERTY_TYPE_LABELS: Record<string, string> = {
  hotel: 'Hotel',
  transit_hotel: 'Transit Hotel',
  sleep_pods: 'Sleep Pods & Capsules',
  capsule_hotel: 'Sleep Pods & Capsules',
  sleep_lounge: 'Sleep Lounge',
  day_room: 'Day Room',
};

export const ACCESS_TYPE_LABELS: Record<string, string> = {
  airside: 'Airside',
  landside: 'Landside',
  terminal_connected: 'Terminal Connected',
};

export const ACCESS_TYPE_BADGE_COLORS: Record<string, string> = {
  airside: 'bg-green-100 text-green-800',
  landside: 'bg-amber-100 text-amber-800',
  terminal_connected: 'bg-blue-100 text-blue-800',
};

export const SELECT_CLASS =
  "w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-action focus:border-transparent outline-none transition bg-white appearance-none bg-[url('data:image/svg+xml;charset=UTF-8,%3csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2212%22%20height%3D%2212%22%20viewBox%3D%220%200%2012%2012%22%3E%3cpath%20fill%3D%22%23333333%22%20d%3D%22M10.293%203.293L6%207.586%201.707%203.293A1%201%200%2000.293%204.707l5%205a1%201%200%20001.414%200l5-5a1%201%200%2010-1.414-1.414z%22%2F%3E%3c%2Fsvg%3E')] bg-[length:12px] bg-[center_right_1rem] bg-no-repeat";

export const INPUT_CLASS =
  "w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-action focus:border-transparent outline-none transition";
